--US STATES TABLE
  CREATE TABLE "SYSTEM"."US_STATES" 
   (	"POSTAL_CODE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"STATE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "US_STATES_PK" PRIMARY KEY ("POSTAL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
-- Countries Table

  CREATE TABLE "SYSTEM"."COUNTRIES" 
   (	"ISOALPHA3_COUNTRYCODE" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("ISOALPHA3_COUNTRYCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- Wyoming Counties table


  CREATE TABLE "SYSTEM"."WY_COUNTIES" 
   (	"COUNTY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "US_COUNTIES_PK" PRIMARY KEY ("COUNTY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- Wyomin Cities table


  CREATE TABLE "SYSTEM"."WY_CITIES" 
   (	"CITY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "WY_CITIES_PK" PRIMARY KEY ("CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- wyoweb login users

  CREATE TABLE "SYSTEM"."UW_USERS" 
   (	"UWYO_EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "UW_USERS_PK" PRIMARY KEY ("UWYO_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
-- uw engagement admins table

  CREATE TABLE "SYSTEM"."UW_ENG_ADMINS" 
   (	"EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "UW_ENG_ADMINS_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UW_ENG_ADMINS_FK1" FOREIGN KEY ("EMAIL")
	  REFERENCES "SYSTEM"."UW_USERS" ("UWYO_EMAIL") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- Event Location table



  CREATE TABLE "SYSTEM"."LOCATION" 
   (	"EVENT_ID" NUMBER NOT NULL ENABLE, 
	"BUILDING_ROOM" VARCHAR2(100 BYTE), 
	"ADDRESS_LINE1" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"ADDRESS_LINE2" VARCHAR2(200 BYTE), 
	"COUNTY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CITY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"STATE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"ZIP" NUMBER NOT NULL ENABLE, 
	"OTHER_CITY" VARCHAR2(100 BYTE), 
	 CONSTRAINT "LOCATION_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "LOCATION_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "SYSTEM"."UW_ENGAGEMENT" ("EVENT_ID") ENABLE, 
	 CONSTRAINT "LOCATION_FK2" FOREIGN KEY ("STATE")
	  REFERENCES "SYSTEM"."US_STATES" ("POSTAL_CODE") ENABLE, 
	 CONSTRAINT "LOCATION_FK3" FOREIGN KEY ("COUNTRY")
	  REFERENCES "SYSTEM"."COUNTRIES" ("ISOALPHA3_COUNTRYCODE") ENABLE, 
	 CONSTRAINT "LOCATION_FK4" FOREIGN KEY ("COUNTY")
	  REFERENCES "SYSTEM"."WY_COUNTIES" ("COUNTY") ENABLE, 
	 CONSTRAINT "LOCATION_FK5" FOREIGN KEY ("CITY")
	  REFERENCES "SYSTEM"."WY_CITIES" ("CITY") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


-- Event Speakers table


  CREATE TABLE "SYSTEM"."SPEAKERS" 
   (	"EVENT_ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"MIDDLE_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	 CONSTRAINT "SPEAKERS_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "SYSTEM"."UW_ENGAGEMENT" ("EVENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- Event Contact info table

  CREATE TABLE "SYSTEM"."CONTACT_INFO" 
   (	"EVENT_ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"SPONSORING_DEPARTMENT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EMAIL_1" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EMAIL_2" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" NUMBER, 
	"WEBSITE" VARCHAR2(100 BYTE), 
	 CONSTRAINT "CONTACT_INFO_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CONTACT_INFO_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "SYSTEM"."UW_ENGAGEMENT" ("EVENT_ID") ENABLE, 
	 CONSTRAINT "CONTACT_INFO_FK2" FOREIGN KEY ("EMAIL_1")
	  REFERENCES "SYSTEM"."UW_USERS" ("UWYO_EMAIL") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--event co-sponsors table


  CREATE TABLE "SYSTEM"."CO_SPONSORS" 
   (	"EVENT_ID" NUMBER NOT NULL ENABLE, 
	"CO_SPONSOR_NAME" VARCHAR2(100 BYTE), 
	"CO_SPONSOR_EMAIL" VARCHAR2(100 BYTE), 
	"CO_SPONSOR_PHONE_NUMBER" NUMBER, 
	"CO_SPONSOR_WEBSITE" VARCHAR2(100 BYTE), 
	 CONSTRAINT "CO_SPONSORS_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CO_SPONSORS_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "SYSTEM"."UW_ENGAGEMENT" ("EVENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- triggers

CREATE OR REPLACE TRIGGER UW_ENGAGEMENT_TRIGGER 
BEFORE INSERT OR UPDATE ON UW_ENGAGEMENT 
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    :new.last_update_date := SYSDATE;
    IF :new.cancelled != :old.cancelled AND :new.cancelled='YES' THEN
      :new.cancellation_date := SYSDATE;
    ELSIF :new.cancelled != :old.cancelled THEN
      :new.cancellation_date := null;
      :new.cancelled_by :=null;
    END IF;
  ELSIF INSERTING THEN
    :new.creation_date := SYSDATE;
  END IF;
END;
