CREATE OR REPLACE TYPE SPEAKER AS OBJECT 
( /* TODO enter attribute and method declarations here */ 
  first_name VARCHAR2(200),
  last_name VARCHAR2(200),
  middle_name VARCHAR2(200),
  email VARCHAR2(200));
  
/  
CREATE TYPE speaker_type AS TABLE OF speaker; 
/
CREATE OR REPLACE TYPE location AS OBJECT 
( /* TODO enter attribute and method declarations here */ 
  building_room VARCHAR2(200),
  address_line1 VARCHAR2(200),
  address_line2 VARCHAR2(200),
  county VARCHAR2(200),
  city VARCHAR2(200),
  state VARCHAR2(200),
  country VARCHAR2(200),
  zip NUMBER);
/

CREATE OR REPLACE TYPE location AS OBJECT 
( /* TODO enter attribute and method declarations here */ 
  building_room VARCHAR2(200),
  address_line1 VARCHAR2(200),
  address_line2 VARCHAR2(200),
  county VARCHAR2(200),
  city VARCHAR2(200),
  state VARCHAR2(200),
  country VARCHAR2(200),
  zip NUMBER,
  CONSTRAINT address_line1_constraint CHECK (address_line1 IS NOT NULL),
  CONSTRAINT county_constraint 
  CHECK (county IN
                ('Albany',
                'Big Horn',
                'Campbell',
                'Carbon',
                'Converse',
                'Crook',
                'Fremont',
                'Goshen',
                'Hot Springs',
                'Johnson',
                'Laramie',
                'Lincoln',
                'Natrona',
                'Niobrara',
                'Park',
                'Platte',
                'Sheridan',
                'Sublette',
                'Sweetwater',
                'Teton',
                'Uninta',
                'Washakie',
                'Weston',
                'Wind River Indian Reservation')),
  
  CONSTRAINT city_constraint 
  CHECK (city IN
                ('Albin',
                'Bar Nunn',
                'Basin',
                'Bear River',
                'Buffalo',
                'Burlington',
                'Burns',
                'Byron',
                'Casper',
                'Cheyenne',
                'Clearmont',
                'Cody',
                'Cowley',
                'Dayton',
                'Deaver',
                'Diamondville',
                'Douglas',
                'Dubois',
                'Edgerton',
                'Evanston',
                'Evansville',
                'Frannie-BigHornCty',
                'Frannie-Park Cty',
                'Gillette',
                'Glendo',
                'Glenrock',
                'Grand Encampment',
                'Granger',
                'Green River',
                'Greybull',
                'Guernsey',
                'Hudson',
                'Hulett',
                'Jackson',
                'Kaycee',
                'Kemmerer',
                'Lander',
                'Laramie',
                'Lingle',
                'Lovell',
                'Lusk',
                'Lyman',
                'Manderson',
                'Meeteetse',
                'Midwest',
                'Mills',
                'Moorcroft',
                'Mountain View',
                'Newcastle',
                'Opal',
                'Pavillion',
                'Pine Bluffs',
                'Pinedale',
                'Powell',
                'Ranchester',
                'Rawlins',
                'Riverton',
                'Rock River',
                'Rock Springs',
                'Rolling Hills',
                'Saratoga',
                'Sheridan',
                'Shoshoni',
                'Star Valley Ranch',
                'Sundance',
                'Ten Sleep',
                'Thermopolis',
                'Torrington',
                'Upton',
                'Wamsutter',
                'Wheatland',
                'Worland',
                'Wright',
                'Yoder',
                'Crowheart',
                'Fort Washakie',
                'Ethete',
                'Kinnear',
                'Arapahoe')),
  
  CONSTRAINT state_constraint 
  CHECK (state="Wyoming"),
  
  CONSTRAINT country_constraint
  CHECK(country="United States")
  );
