CREATE TABLE CO_SPONSORS 
(
  EVENT_ID NUMBER NOT NULL 
, CO_SPONSOR_NAME VARCHAR2(100 BYTE) 
, CO_SPONSOR_EMAIL VARCHAR2(100 BYTE) 
, CO_SPONSOR_PHONE_NUMBER NUMBER 
, CO_SPONSOR_WEBSITE VARCHAR2(100 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE CO_SPONSORS
ADD CONSTRAINT CO_SPONSORS_FK1 FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES UW_ENGAGEMENT
(
  EVENT_ID 
)
ENABLE;
