CREATE TABLE CONTACT_INFO 
(
  EVENT_ID NUMBER NOT NULL 
, FIRST_NAME VARCHAR2(100 BYTE) 
, LAST_NAME VARCHAR2(100 BYTE) 
, SPONSORING_DEPARTMENT VARCHAR2(100 BYTE) NOT NULL 
, EMAIL_1 VARCHAR2(100 BYTE) NOT NULL 
, EMAIL_2 VARCHAR2(100 BYTE) 
, PHONE_NUMBER NUMBER 
, WEBSITE VARCHAR2(100 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE UNIQUE INDEX CONTACT_INFO_PK ON CONTACT_INFO (EVENT_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE CONTACT_INFO
ADD CONSTRAINT CONTACT_INFO_PK PRIMARY KEY 
(
  EVENT_ID 
)
USING INDEX CONTACT_INFO_PK
ENABLE;

ALTER TABLE CONTACT_INFO
ADD CONSTRAINT CONTACT_INFO_FK1 FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES UW_ENGAGEMENT
(
  EVENT_ID 
)
ENABLE;
