CREATE TABLE LOCATION 
(
  EVENT_ID NUMBER NOT NULL 
, BUILDING_ROOM VARCHAR2(100 BYTE) 
, ADDRESS_LINE1 VARCHAR2(200 BYTE) NOT NULL 
, ADDRESS_LINE2 VARCHAR2(200 BYTE) 
, COUNTY VARCHAR2(100 BYTE) NOT NULL 
, CITY VARCHAR2(100 BYTE) NOT NULL 
, STATE VARCHAR2(2 BYTE) NOT NULL 
, COUNTRY VARCHAR2(3 BYTE) NOT NULL 
, ZIP NUMBER NOT NULL 
, OTHER_CITY VARCHAR2(100 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE UNIQUE INDEX LOCATION_PK ON LOCATION (EVENT_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE LOCATION
ADD CONSTRAINT LOCATION_PK PRIMARY KEY 
(
  EVENT_ID 
)
USING INDEX LOCATION_PK
ENABLE;

ALTER TABLE LOCATION
ADD CONSTRAINT LOCATION_FK1 FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES UW_ENGAGEMENT
(
  EVENT_ID 
)
ENABLE;

ALTER TABLE LOCATION
ADD CONSTRAINT LOCATION_CHK1 CHECK 
(city!='Other' OR other_city IS NOT NULL)
ENABLE;
