CREATE TABLE SPEAKERS 
(
  EVENT_ID NUMBER NOT NULL 
, FIRST_NAME VARCHAR2(100 BYTE) 
, MIDDLE_NAME VARCHAR2(100 BYTE) 
, LAST_NAME VARCHAR2(100 BYTE) 
, EMAIL VARCHAR2(100 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE SPEAKERS
ADD CONSTRAINT SPEAKERS_FK1 FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES UW_ENGAGEMENT
(
  EVENT_ID 
)
ENABLE;
