CREATE TABLE UW_ENG_ADMINS 
(
  EMAIL VARCHAR2(100 BYTE) NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE UNIQUE INDEX UW_ENG_ADMINS_PK ON UW_ENG_ADMINS (EMAIL ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE UW_ENG_ADMINS
ADD CONSTRAINT UW_ENG_ADMINS_PK PRIMARY KEY 
(
  EMAIL 
)
USING INDEX UW_ENG_ADMINS_PK
ENABLE;
